Bugfix: EntityMalformedException: Missing bundle property on entity of type node. in entity_extract_ids()
While browsing /admin/config/workflow/rules, field_title_short causes:
  EntityMalformedException: Missing bundle property on entity of type node. in entity_extract_ids() (line 7389 of /var/www/development/includes/common.inc).

I identified the line of code where the problem is triggered:
  field_permissions/field_permissions.module:178

The function _field_permissions_field_edit_access() has a comment about a warning (not this error) and references: https://drupal.org/node/1301522.
This commit applies the patch supplied there for drupal 7.